Repository jykuo-love-shiritori/twp, pull requests merged in 2023-12, with the labels that each got.

#67 Seller
  .dockerignore
  .gitignore
  db/admin.sql.go
  db/buyer.sql.go
  db/general.sql.go
  db/migrations/000001_db_setup.up.sql
  db/models.go
  db/queries/admin.sql
  db/queries/general.sql
  db/queries/seller.sql
  db/queries/test.sql
  db/queries/test_temp.sql
  db/queries/user.sql
  db/seller.sql.go
  db/test.sql.go
  db/user.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  dummy_test.go
  pkg/common/common.go
  pkg/router/admin.go
  pkg/router/router.go
  pkg/router/seller.go
  pkg/router/user.go
  sqlc.yaml
  test/main.go
Labels: bug, documentation, enhancement, backend, refactor

#84 [backend] update schema
  db/admin.sql.go
  db/buyer.sql.go
  db/general.sql.go
  db/migrations/000001_db_setup.up.sql
  db/models.go
  db/queries/test.sql
  db/queries/user.sql
  db/seller.sql.go
  db/test.sql.go
  db/user.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  pkg/auth/signup.go
  sqlc.yaml
  test/main.go
Labels: backend, refactor

#79 [backend] Uploadfile minio
  .dockerignore
  .example.env
  db/general.sql.go
  db/models.go
  db/queries/seller.sql
  db/seller.sql.go
  db/test.sql.go
  docker-compose.yml
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  main.go
  minio/minio_operation.go
  pkg/common/common.go
  pkg/router/router.go
  pkg/router/seller.go
  sqlc.yaml
  test/db/main.go
  test/minio/main.go
  test/minio/test.jpg
Labels: enhancement, backend

#80 Oauth2
  db/migrations/000002_refresh_token_expire.down.sql
  db/migrations/000002_refresh_token_expire.up.sql
  db/models.go
  db/queries/user.sql
  db/test.sql.go
  db/user.sql.go
  frontend/.example.env
  frontend/src/App.tsx
  frontend/src/components/APItest.tsx
  frontend/src/components/AuthProvider.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/ProtectedBoundary.tsx
  frontend/src/lib/Auth.ts
  frontend/src/main.tsx
  frontend/src/pages/home/index.tsx
  frontend/src/pages/user/authorize.tsx
  frontend/src/pages/user/callback.tsx
  frontend/src/pages/user/login.tsx
  frontend/src/vite-env.d.ts
  frontend/tsconfig.json
  frontend/vite.config.ts
  main.go
  pkg/auth/authorize.go
  pkg/auth/common.go
  pkg/auth/logout.go
  pkg/auth/middleware.go
  pkg/auth/refresh.go
  pkg/auth/signup.go
  pkg/auth/store.go
  pkg/auth/token.go
  pkg/auth/verify_test.go
  pkg/common/is_env.go
  pkg/constants/role.go
  pkg/router/router.go
  test/auth/main.go
Labels: enhancement, frontend, backend

#88 [backend] api seller/user
  .example.env
  db/admin.sql.go
  db/general.sql.go
  db/models.go
  db/queries/seller.sql
  db/queries/user.sql
  db/seller.sql.go
  db/test.sql.go
  db/user.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  minio/minio_operation.go
  pkg/common/common.go
  pkg/router/router.go
  pkg/router/seller.go
  pkg/router/seller/coupon.go
  pkg/router/seller/order.go
  pkg/router/seller/product.go
  pkg/router/seller/shop.go
  pkg/router/seller/tag.go
  pkg/router/user/user.go
  sqlc.yaml
Labels: documentation, backend, refactor

#87 [Backend] Partial API Implementation 📄
  db/admin.sql.go
  db/buyer.sql.go
  db/general.sql.go
  db/init_db.go
  db/migrations/000001_db_setup.up.sql
  db/migrations/000003_text_search.down.sql
  db/migrations/000003_text_search.up.sql
  db/models.go
  db/queries/admin.sql
  db/queries/buyer.sql
  db/queries/general.sql
  db/seller.sql.go
  db/test.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  minio/minio_operation.go
  pkg/common/common.go
  pkg/common/news.go
  pkg/constants/constant.go
  pkg/router/admin/coupon.go
  pkg/router/admin/report.go
  pkg/router/admin/user.go
  pkg/router/buyer.go
  pkg/router/buyer/cart.go
  pkg/router/buyer/checkout.go
  pkg/router/buyer/common.go
  pkg/router/buyer/coupon.go
  pkg/router/buyer/order.go
  pkg/router/buyer/product.go
  pkg/router/general.go
  pkg/router/general/common.go
  pkg/router/general/search.go
  pkg/router/general/shop.go
  pkg/router/general/tag.go
  pkg/router/router.go
  pkg/router/seller/tag.go
  sqlc.yaml
Labels: documentation, backend, refactor

#89 [frontend] Cart Section
  frontend/.example.env
  frontend/public/resources/Carts.json
  frontend/public/resources/Checkout.json
  frontend/public/resources/UsableCoupons.json
  frontend/src/App.tsx
  frontend/src/components/AdminButtons.tsx
  frontend/src/components/BuyerButtons.tsx
  frontend/src/components/Cart.tsx
  frontend/src/components/CartGroup.tsx
  frontend/src/components/CartItem.tsx
  frontend/src/components/CartProduct.tsx
  frontend/src/components/CheckoutItem.tsx
  frontend/src/components/CheckoutItemCoupon.tsx
  frontend/src/components/CouponItem.tsx
  frontend/src/components/CouponItemTemplate.tsx
  frontend/src/components/HistoryItem.tsx
  frontend/src/components/HistoryProduct.tsx
  frontend/src/components/ManageUser.tsx
  frontend/src/components/ProtectedBoundary.tsx
  frontend/src/components/SellerButtons.tsx
  frontend/src/components/TButton.tsx
  frontend/src/components/style.css
  frontend/src/lib/Functions.ts
  frontend/src/pages/cart/index.tsx
  frontend/src/pages/coupon/index.tsx
  frontend/src/pages/user/admin/allCoupons/[adminCouponID].tsx
  frontend/src/pages/user/admin/allCoupons/index.tsx
  frontend/src/pages/user/admin/allCoupons/newCoupon.tsx
  frontend/src/pages/user/buyer/cart/boughtData.json
  frontend/src/pages/user/buyer/cart/index.tsx
  frontend/src/pages/user/buyer/history/[historyID].tsx
  frontend/src/pages/user/buyer/history/index.tsx
  frontend/src/pages/user/login.tsx
  frontend/src/pages/user/seller/allCoupons/[sellerCouponID].tsx
  frontend/src/pages/user/seller/allCoupons/index.tsx
  frontend/src/pages/user/seller/allCoupons/newCoupon.tsx
  frontend/src/pages/user/seller/allShipments/index.tsx
  frontend/src/pages/user/shop/SellerCoupons.tsx
  frontend/src/vite-env.d.ts
Labels: frontend

#92 Finished signup functionality
  db/queries/user.sql
  db/user.sql.go
  pkg/auth/context.go
  pkg/auth/middleware.go
  pkg/auth/signup.go
  pkg/auth/verify_test.go
Labels: backend

#98 [backend] Fix #97
  db/buyer.sql.go
  db/queries/buyer.sql
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  pkg/router/buyer/checkout.go
  pkg/router/buyer/coupon.go
  pkg/router/buyer/order.go
Labels: bug, documentation, backend

#96 [frontend] Sign Up api
  frontend/package-lock.json
  frontend/src/components/Cart.tsx
  frontend/src/components/WarningModal.tsx
  frontend/src/lib/Functions.ts
  frontend/src/lib/Status.tsx
  frontend/src/pages/user/authorize.tsx
  frontend/src/pages/user/callback.tsx
  frontend/src/pages/user/login.tsx
  frontend/src/pages/user/signup.tsx
  pkg/auth/authorize.go
Labels: frontend

#105 [Backend] 無情的修改資料庫綱要
  db/buyer.sql.go
  db/migrations/000001_db_setup.up.sql
  db/models.go
  db/queries/buyer.sql
  db/queries/seller.sql
  db/queries/test.sql
  db/queries/user.sql
  db/seller.sql.go
  db/test.sql.go
  db/user.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  pkg/router/admin/coupon.go
  pkg/router/buyer/checkout.go
  pkg/router/seller/order.go
Labels: bug, backend, refactor

#99 [frontend] Info pages api
  .example.env
  frontend/.example.env
  frontend/src/assets/images/defaultUserIcon.gif
  frontend/src/lib/Status.tsx
  frontend/src/pages/user/buyer/info/index.tsx
  frontend/src/pages/user/seller/info/index.tsx
  frontend/vite.config.ts
Labels: frontend

#102 Fix seller/user swagger api
  db/buyer.sql.go
  db/queries/buyer.sql
  db/queries/seller.sql
  db/seller.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  pkg/router/router.go
  pkg/router/seller/order.go
  pkg/router/seller/shop.go
  pkg/router/seller/tag.go
  pkg/router/user/user.go
Labels: bug, backend

#117 copy dotenv file in Dockerfile
  Dockerfile
Labels: bug, devops

#120 [backend] Fix disable user return wrong message
  db/admin.sql.go
  db/queries/admin.sql
  pkg/router/admin/user.go
Labels: bug, backend

#100 [frontend] CreditCard, Password api
  frontend/src/pages/user/buyer/before.json
  frontend/src/pages/user/buyer/security/CreditCard.tsx
  frontend/src/pages/user/buyer/security/NewCard.tsx
  frontend/src/pages/user/buyer/security/Password.tsx
  frontend/src/pages/user/buyer/security/creditCard.json
  frontend/src/pages/user/buyer/user.json
Labels: frontend

#122 [backend] more swagger
  db/queries/seller.sql
  db/seller.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  pkg/router/seller/coupon.go
  pkg/router/seller/product.go
Labels: documentation, backend

#123 Fix presigned url
  .example.env
  frontend.go
  main.go
  minio/minio_operation.go
  pkg/constants/path.go
  pkg/image/handler.go
  pkg/image/url.go
  pkg/router/admin/report.go
  pkg/router/admin/user.go
  pkg/router/buyer/cart.go
  pkg/router/buyer/order.go
  pkg/router/general/common.go
  pkg/router/general/search.go
  pkg/router/general/shop.go
  pkg/router/seller/order.go
  pkg/router/seller/product.go
  pkg/router/seller/shop.go
  pkg/router/user/user.go
Labels: bug, backend
