Repository jykuo-love-shiritori/twp, pull requests merged in 2023-11, with the labels that each got.

#25 Fix #16
  frontend.go
  main.go
  pkg/constants/environment.go
  pkg/constants/path.go
  pkg/environment/environment.go
  pkg/router/router.go
Labels: backend

#26 Added Github Actions for Backend
  .github/workflows/checks.yml
  .golangci.yml
  dummy_test.go
Labels: enhancement, devops

#30 [backend] update db setup
  db/migrations/000001_db_setup.down.sql
  db/migrations/000001_db_setup.up.sql
Labels: backend

#33 [backend] fix wrong syntax
  db/migrations/000001_db_setup.up.sql
Labels: bug, backend

#48 [backend] Add tags to override sqlc generated struct
  db/db.go
  db/migrations/000001_db_setup.up.sql
  db/models.go
  db/queries/test_temp.sql
  db/test_temp.sql.go
  pkg/router/admin.go
  pkg/router/buyer.go
  pkg/router/general.go
  pkg/router/seller.go
  pkg/router/user.go
  sqlc.yaml
Labels: backend

#53 Add frontend CI checks
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: devops

#56 Update PR template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: documentation

#60 Fix PR template & minor change
  .github/PULL_REQUEST_TEMPLATE.md
Labels: bug, documentation

#59 Create LICENSE
  LICENSE
Labels: documentation

#65 Pool
  db/init_db.go
  db/models.go
  db/queries/test_temp.sql
  db/test_temp.sql.go
  go.mod
Labels: backend

#66 Backend sync
  .example.env
  db/queries/user.sql
  db/user.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  go.mod
  go.sum
  main.go
  pkg/auth/authorize.go
  pkg/auth/common.go
  pkg/auth/logout.go
  pkg/auth/middleware.go
  pkg/auth/signup.go
  pkg/auth/store.go
  pkg/auth/token.go
  pkg/common/placeholder.go
  pkg/constants/role.go
  pkg/router/router.go
  pkg/router/user.go
  test/auth/main.go
Labels: backend

#61 [frontend] check ViewShop & Order section
  frontend/src/App.tsx
  frontend/src/components/CartItem.tsx
  frontend/src/components/Forbidden.tsx
  frontend/src/components/GoodsItem.tsx
  frontend/src/components/HistoryItem.tsx
  frontend/src/components/Info.tsx
  frontend/src/components/InfoItem.tsx
  frontend/src/components/NavBar.tsx
  frontend/src/components/NotFound.tsx
  frontend/src/components/PasswordItem.tsx
  frontend/src/components/QuantityBar.tsx
  frontend/src/components/SellerButtons.tsx
  frontend/src/components/Unauthorized.tsx
  frontend/src/components/style.css
  frontend/src/pages/cart/index.tsx
  frontend/src/pages/discover/[goodsID].tsx
  frontend/src/pages/discover/index.tsx
  frontend/src/pages/user/authorize.tsx
  frontend/src/pages/user/buyer/history/[historyID].tsx
  frontend/src/pages/user/buyer/history/index.tsx
  frontend/src/pages/user/buyer/index.tsx
  frontend/src/pages/user/buyer/info/index.tsx
  frontend/src/pages/user/buyer/security/NewCard.tsx
  frontend/src/pages/user/buyer/security/Password.tsx
  frontend/src/pages/user/login.tsx
  frontend/src/pages/user/seller/allProducts/NewGoods.tsx
  frontend/src/pages/user/seller/allProducts/[sellerGoodsID].tsx
  frontend/src/pages/user/seller/allProducts/index.tsx
  frontend/src/pages/user/seller/allShipments/index.tsx
  frontend/src/pages/user/seller/index.tsx
  frontend/src/pages/user/shop/Shop.tsx
  frontend/src/pages/user/shop/index.tsx
  frontend/src/pages/user/signup.tsx
  frontend/src/style/global.css
Labels: frontend

#73 [frontend] Remove unused property at home page
  .github/workflows/frontend.yml
  frontend/src/pages/home/index.tsx
Labels: frontend

#70 [Backend] Backend Sync
  db/admin.sql.go
  db/buyer.sql.go
  db/general.sql.go
  db/migrations/000001_db_setup.down.sql
  db/migrations/000001_db_setup.up.sql
  db/models.go
  db/queries/.gitkeep
  db/queries/admin.sql
  db/queries/buyer.sql
  db/queries/general.sql
  db/test_temp.sql.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  pkg/auth/logout.go
  pkg/common/common.go
  pkg/constants/constant.go
  pkg/constants/strings.go
  pkg/router/admin.go
  pkg/router/buyer.go
  pkg/router/general.go
  pkg/router/router.go
  pkg/router/seller.go
  pkg/router/user.go
  sqlc.yaml
  test/main.go
Labels: documentation, backend
